name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in workspace for debugging
        run: |
          ls -la
          # echo "Listing utils/virtual_space_sim/ :" # No longer needed as files are at root
          # ls -la utils/virtual_space_sim/            # No longer needed

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          # Path is now relative to the root of the checkout
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        # Files are at the root, no need to cd
        run: npm ci

      - name: Build project
        # Files are at the root, no need to cd
        run: npm run build
        env:
          VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_TOKEN }}

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path is now relative to the root of the checkout
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
